apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: order-service
data:
  Authentication__Authority: "https://monolith.example.com"
  Authentication__Audience: "order_service"
